<a href="https://colab.research.google.com/github/vishwas0297/pyhton/blob/vishwas-0297/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([1,3,0],float)
print(a>2)

[False  True False]


In [ ]:
print(a[0])

1.0


In [ ]:
print(a[-1])

0.0


In [ ]:
print(a[-2])

3.0


In [ ]:
import numpy as np
a = np.array([2,3,4])
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
b = np.array([2,3,4])
print(type(b))

<class 'numpy.ndarray'>


In [ ]:
a = np.array([[1,3,5],[2,4,6]])
print(a[0][0])

1


In [ ]:
a = np.array([[1,3,5],[2,4,6]])
print(a[0][0])

1


In [ ]:
arr=np.zeros((3,3),int)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
arr=np.empty((3,4))
print(arr)

[[4.78191695e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [ ]:
arr=np.arange(0,2,0.3)
print(arr)

[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [ ]:
arr=np.linspace(0,2,9)
print(arr)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [ ]:
import numpy as np
x = np.random.randint(-20,49,5)

print(x)

[ 3  7 -4  0 28]


In [ ]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]
